#cloud-config
packages:
  - openssh-server
  - epel-release
  - wget 
  - net-tools

runcmd:
  - yum install -y tar wget
  - wget -O /tmp/victoria-metrics-linux-amd64-v1.89.1-cluster.tar.gz https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.89.1/victoria-metrics-linux-amd64-v1.89.1-cluster.tar.gz
  - tar -C /usr/local/bin/ -xvzf /tmp/victoria-metrics-linux-amd64-v1.89.1-cluster.tar.gz
  - rm -f /tmp/victoria-metrics-linux-amd64-v1.89.1-cluster.tar.gz
  - mkdir -p /data/vmstorage-data
  - systemctl enable vmstorage.service
  - systemctl restart vmstorage.service 
  - systemctl enable vminsert.service
  - systemctl restart vminsert.service
  - systemctl enable vmselect.service
  - systemctl restart vmselect.service

write_files:
  - path: /etc/systemd/system/vmstorage.service
    permissions: "0644"
    owner: root
    content: |
      [Unit]
      Description=Vmstorage Server
      After=network.target
 
      [Service]
      Restart=on-failure
      WorkingDirectory=/tmp
      ExecStart=/usr/local/bin/vmstorage-prod -loggerTimezone Asia/Tokyo -storageDataPath /data/vmstorage-data -httpListenAddr=:8482 -vminsertAddr=:8400 -vmselectAddr=:8401 -retentionPeriod=5y

      [Install]
      WantedBy=multi-user.target
  - path: /etc/systemd/system/vminsert.service 
    permissions: "0644"
    owner: root
    content: |
      [Unit]
      Description=Vminsert Server
      After=network.target

      [Service]
      Restart=on-failure
      WorkingDirectory=/tmp
      ExecStart=/usr/local/bin/vminsert-prod  -httpListenAddr=:8480 -storageNode=10.128.15.100:8400,10.128.15.101:8400,10.128.15.102:8400 -opentsdbListenAddr=:4242

      [Install]
       WantedBy=multi-user.target
  - path: /etc/systemd/system/vmselect.service
    permissions: "0644"
    owner: root
    content: |
      [Unit]
      Description=Vmselect Server
      After=network.target

      [Service]
      Restart=on-failure
      WorkingDirectory=/tmp
      ExecStart=/usr/local/bin/vmselect-prod -httpListenAddr=:8481 -storageNode=10.128.15.100:8401,10.128.15.101:8401,10.128.15.102:8401 -search.maxSeries=1000000 -search.maxUniqueTimeseries=1000000000 -search.maxQueryDuration=30m -search.maxSamplesPerQuery=100000000000 -search.latencyOffset=1s

      [Install]
      WantedBy=multi-user.target
