{
 "title": "Barreleye - EXAScaler",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Number of inode in MDT0000",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mdt_filesinfo_used{mdt_index=\"MDT0000\"})",
     "legendFormat": "__auto",
     "measurement": "mdt_filesinfo_used",
     "query": "SELECT last(\"value\") FROM \"mdt_filesinfo_used\" WHERE (\"mdt_index\" = 'MDT0000') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "mdt_index", "operator": "=", "value": "MDT0000" }
     ]
    }
   ]
  },
  {
   "title": "Number of inode in MDT0001",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mdt_filesinfo_used{mdt_index=\"MDT0001\"})",
     "legendFormat": "__auto",
     "measurement": "mdt_filesinfo_used",
     "query": "SELECT last(\"value\") FROM \"mdt_filesinfo_used\" WHERE (\"mdt_index\" = 'MDT0000') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "mdt_index", "operator": "=", "value": "MDT0000" }
     ]
    }
   ]
  },
  {
   "title": "Number of inode in MDT0002",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mdt_filesinfo_used{mdt_index=\"MDT0002\"})",
     "legendFormat": "__auto",
     "measurement": "mdt_filesinfo_used",
     "query": "SELECT last(\"value\") FROM \"mdt_filesinfo_used\" WHERE (\"mdt_index\" = 'MDT0000') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "mdt_index", "operator": "=", "value": "MDT0000" }
     ]
    }
   ]
  },
  {
   "title": "Number of inode in MDT0003",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mdt_filesinfo_used{mdt_index=\"MDT0003\"})",
     "legendFormat": "__auto",
     "measurement": "mdt_filesinfo_used",
     "query": "SELECT last(\"value\") FROM \"mdt_filesinfo_used\" WHERE (\"mdt_index\" = 'MDT0000') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "mdt_index", "operator": "=", "value": "MDT0000" }
     ]
    }
   ]
  },
  {
   "title": "Capacity Usage of Lustre",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "used",
     "expr": "sum(ost_kbytesinfo_used)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "fs_name" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "ost_kbytesinfo_used",
     "query": "SELECT sum(\"value\") FROM \"ost_kbytesinfo_used\" WHERE $timeFilter GROUP BY time(1m), \"fs_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lustre Aggregated CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "system",
     "expr": "sum(aggregation.cpu-average.cpu.user)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "aggregation.cpu-average.cpu.system",
     "query": "SELECT sum(\"value\") FROM \"aggregation.cpu-average.cpu.system\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "user",
     "expr": "sum(aggregation.cpu-average.cpu.system)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "aggregation.cpu-average.cpu.user",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Quota Accounting (Capacity)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "alias": "UID=$tag_user_id",
     "expr": "sum by(user_id) (ost_acctuser_samples)",
     "groupBy": [
      { "params": [ "user_id" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "cq_ost_acctuser_samples_by_user_id",
     "query": "SELECT last(\"sum\") FROM \"cq_ost_acctuser_samples_by_user_id\" WHERE (\"optype\" = 'usage_kbytes') AND $timeFilter GROUP BY \"user_id\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "optype", "operator": "=", "value": "usage_kbytes" }
     ]
    }
   ]
  },
  {
   "title": "Quota Accounting (inode)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "alias": "UID=$tag_user_id",
     "expr": "sum by(user_id) (mdt_acctuser_samples)",
     "groupBy": [
      { "params": [ "user_id" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "cq_ost_acctuser_samples_by_user_id",
     "query": "SELECT last(\"sum\") FROM \"cq_ost_acctuser_samples_by_user_id\" WHERE (\"optype\" = 'usage_kbytes') AND $timeFilter GROUP BY \"user_id\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "optype", "operator": "=", "value": "usage_kbytes" }
     ]
    }
   ]
  },
  {
   "title": "Lustre Aggregated B/W",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_optype",
     "expr": "sum by(optype) (ost_stats_bytes)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "optype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "cq_ost_stats_bytes_by_optype",
     "query": "SELECT sum(\"sum\") FROM \"cq_ost_stats_bytes_by_optype\" WHERE $timeFilter GROUP BY time(1m), \"optype\" fill(null)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lustre Aggregated Metadata",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$tag_optype",
     "expr": "sum by(optype) (md_stats)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "optype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "cq_md_stats_by_optype",
     "query": "SELECT sum(\"sum\") FROM \"cq_md_stats_by_optype\" WHERE $timeFilter GROUP BY time(1m), \"optype\" fill(null)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lustre Bulk RPC Size(Write)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(size) (ost_brw_stats_rpc_bulk_samples{field=\"write_sample\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lustre Bulk RPC Size(Read)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(size) (ost_brw_stats_rpc_bulk_samples{field=\"read_sample\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lustre Top B/W Activity per USER",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_ll_job_uid",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ll_job_uid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cq_ost_jobstats_bytes_by_ll_job_uid",
     "query": "SELECT sum(\"sum\") FROM \"cq_ost_jobstats_bytes_by_ll_job_uid\" WHERE (\"optype\" = 'sum_write_bytes' OR \"optype\" = 'sum_read_bytes') AND $timeFilter GROUP BY time(1m), \"ll_job_uid\" fill(null)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "optype", "operator": "=", "value": "sum_write_bytes" },
      { "condition": "OR", "key": "optype", "operator": "=", "value": "sum_read_bytes" }
     ]
    }
   ]
  },
  {
   "title": "Lustre Top Metadata Activity per USER",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$tag_ll_job_uid",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ll_job_uid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cq_mdt_jobstats_samples_by_ll_job_uid",
     "query": "SELECT sum(\"sum\") FROM \"cq_mdt_jobstats_samples_by_ll_job_uid\" WHERE $timeFilter GROUP BY time(1m), \"ll_job_uid\" fill(null)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}